- Makefile
force the usage of python2.7 on systems where /usr/bin/python points to python3.x
fixes issue #12
> fix(Makefile): force python2.7 in virtualenv

- src/mako/deps.mako
clean-all-docs and clean-all-cli aren't valid targets. The current mako
template causes `make clean` to abend reporting that it can't make these
targets.
> fix(make): fix clean target for docs/cli

- src/mako/api/lib/mbuild.mako
Fixes #146. Tested with `google_gmail1::UserMessageListCall` with multiple label IDs.
> Send repeated properties as repeated query parameters

- gen/cloudbilling1/src/lib.rs.in
- gen/cloudresourcemanager1/src/lib.rs.in
- gen/cloudresourcemanager1_beta1/src/lib.rs.in
- gen/dataproc1/src/lib.rs.in
- gen/genomics1/src/lib.rs.in
- gen/iam1/src/lib.rs.in
- gen/logging2_beta1/src/lib.rs.in
- gen/monitoring3/src/lib.rs.in
- gen/people1/src/lib.rs.in
- gen/proximitybeacon1_beta1/src/lib.rs.in
- gen/pubsub1/src/lib.rs.in
- gen/pubsub1_beta2/src/lib.rs.in
- gen/storagetransfer1/src/lib.rs.in
- gen/youtubereporting1/src/lib.rs.in
- src/mako/api/lib/mbuild.mako
I'm not sure if this is the best solution, or valid for every API, I haven't dug too much in the code generation templates (you probably know best!)
I hit this issue when writing an example client for Google Cloud Pubsub: Hitting the URL `https://pubsub.googleapis.com/v1/projects%2Fsanguine-rhythm-105020%2Fsubscriptions%2Frust_authd_sub_1?alt=json` produces a 404 error, but it works with `https://pubsub.googleapis.com/v1/projects/sanguine-rhythm-105020/subscriptions/rust_authd_sub_1?alt=json`.
The general change is basically not encoding `/` in URLs, and the `DEFAULT_ENCODE_SET` does that.
(also, I whaven't regenerated the APIs as I didn't feel like hunting after the issue that stops python from working right on my machine...)
> URL-encoding '/' in URLs is not accepted by Google APIs

- gen/appengine1/src/lib.rs.in
- gen/appengine1_beta4/src/lib.rs.in
- gen/appengine1_beta5/src/lib.rs.in
- gen/classroom1/src/lib.rs.in
- gen/clouddebugger2/src/lib.rs.in
- gen/cloudresourcemanager1/src/lib.rs.in
- gen/cloudresourcemanager1_beta1/src/lib.rs.in
- gen/cloudtrace1/src/lib.rs.in
- gen/dataproc1/src/lib.rs.in
- gen/genomics1/src/lib.rs.in
- gen/iam1/src/lib.rs.in
- gen/logging2_beta1/src/lib.rs.in
- gen/monitoring3/src/lib.rs.in
- gen/proximitybeacon1_beta1/src/lib.rs.in
- gen/pubsub1/src/lib.rs.in
- gen/pubsub1_beta2/src/lib.rs.in
- gen/storagetransfer1/src/lib.rs.in
- gen/youtube3/src/lib.rs.in
- gen/youtubereporting1/src/lib.rs.in
- src/mako/api/lib/schema.mako
Null structs (`struct Foo;`) cause the following error when trying to
deserialize an empty JSON object `{}` into them:
```
JsonDecodeError("{}\n", Syntax(InvalidType(Map), 1, 1))`
```
string representation:
```
invalid type: map at line 1 column 1: {}
```
The optional struct member prevents this error.
> fix(api types): Add an unused field to empty API types.

- src/mako/deps.mako
Some google discovery URLs contain `$discovery` or other variants,
causing the calls to wget to interpret `$d` as an environment variable
instead of a literal. An example is:
`https://logging.googleapis.com/$discovery/rest?version=v2`.
To fix this, the `$` has been escaped so that wget fetches the URL as
expected.
> fix(discovery): handle discovery urls with $

- src/mako/Cargo.toml.mako
You guessed it, again related to the openssl upgrade in dermesser/yup-oauth2#51. As long as the API crates depend on openssl 0.7 via hyper 0.9, any client using the APIs won't build, because yup-oauth2 pulls in openssl 0.9 (...because openssl 0.7 doesn't build on Mac). It's one big yak to shave, and I'm sorry for all the trouble :(
Please regenerate and publish afterwards, if possible.
> chore(deps): Update hyper for generated crates to ^0.10

- src/mako/index.html.mako
I believe I've figured out why the lines were getting messed up. Basically, some API names were exceeding the 300px allocated to them by `.lib`, so they were being pushed down to a new line. This then messed everything up for the line below so that it starts 300px in.
I converted from the old span + br way of formatting to using tables to keep everything laid out. I hope you don't mind, but I added a link tag to pull in [Bootstrap]'s css from their CDN to make things look pretty.
At the moment the page looks something like this:
(Fixes #166)
[Bootstrap]: http://getbootstrap.com/getting-started/#download-cdn
> Updated index.html documentation template

- .travis.yml
- Makefile
mkdocs depends on tornado that fails to compile on Python before 2.7.9.
When running in Travis not using the Python language a very old version
of Python is used.
This commit adds pyenv and uses it to ensure Travis Python is viable and
stable. This also updates virtualenv to the latest version.
This fixes #203
> core(ci): Fix version of Python used on Travis

- src/mako/api/lib/lib.mako
In the section that describes setting up the Cargo.toml, add the
required dependencies, and note that `hyper` and `hyper-rustls` are not
the latest versions. This helps new users get started quicker and
easier.
Related to #173
> docs(LIB): Add dependencies to README

- etc/api/shared.yaml
- src/mako/deps.mako
Wget leaves empty files when getting a 404. This causes JSON parse errors later on instead of the expected file not found message.
This is caused by some API versions been listed but not existing. Therefore I have added new code to be able to blacklist versions of APIs.
> Removed apis

- src/rust/api/cmn.rs
- src/rust/cli/cmn.rs
change `remove_json_null_values()` to properly remove nulls from and recurse into arrays google_firestore1_beta1's `CommitRequest` contains an array of `Write` objects which can ultimately contain `Value` members that need to have nulls removed to avoid sending multiple types of values which generates a 400 response
fixes calls to google_firestore1_beta1's `hub.projects().databases_documents_commit()`
> fix(rust): teach remove_json_null_values about arrays

- src/mako/index.html.mako
Use the W3 standard "lang" attribute on the "html" tag to provide context for browsers and screen
readers.
Context: Chrome has a language heuristic that determines the page is in Portuguese. It displays the "Translate this page" dialog. Adding the "lang" attribute context should prevent this dialog.
Reference: https://www.w3.org/International/questions/qa-html-language-declarations
> docs: add lang attribute to docs index

- src/mako/api/lib/mbuild.mako
Fixes errors in e.g. drive3 API not getting passed to delegate error handlers.
An ErrorResponse is basically a ServerError wrapped in an "error" object. See e.g. https://developers.google.com/drive/api/v3/handle-errors
A few other APIs that I randomly sampled could probably be helped by this also, e.g. the youtube API.
> Extend attempted error message parsing to also cover ErrorResponse objects

- src/mako/deps.mako
In some environments, a variable-existence test in a template was
yielding a false negative which resulted in the template not generating
'-force' targets for API JSON files, even when the `FETCH_APIS`
environment variable was set during template rendering.
This commit adjusts the way the test for the variable presence is done
such that the '-force' targets now render when they should.
> Fix '-force' target generation for JSON schemata.

- etc/api/pubsub/v1/pubsub-api.json
- gen/pubsub1-cli/Cargo.toml
- gen/pubsub1-cli/README.md
- gen/pubsub1-cli/mkdocs.yml
- gen/pubsub1-cli/src/main.rs
- gen/pubsub1/Cargo.toml
- gen/pubsub1/README.md
- gen/pubsub1/src/lib.rs
Since the last time the PubSub v1 schema was fetched from Discovery in
April, Google has added new API features: namely, subscription filters
and retry policies.  This update to the JSON schema and its generated
code bring in support for these features.
> Update the PubSub schema to include new API features.

- etc/bin/mako-render
- requirements.txt
- src/mako/api/lib/mbuild.mako
- src/rust/api/client.rs
I found a bug in the code preventing be from uploading to Google Drive, the fix was pretty simple, one just need to add the `url` to the request, from some reason that was missing.
I assume that this bug also exist for all the other APIs there has an upload feature, because the code is the same for all of them.
**Bonus/Note:**
- Bumped the python lib used to generate everything to the newest version, I was unable to install the old ones any more. It seems to have caused by a deprecation of a library.
- Found some unused code, which I removed  
`let url = upload_url.as_ref().and_then(|s| Some(url::Url::parse(s).unwrap())).unwrap();`
> Bug-fix for the upload error: Failed at uploading 'client requires absolute-form URIs

- src/rust/api/client.rs
The retry logic of the resumable uploads would continue to the next chunk even if the previous chunk was not successfully uploaded. This would cause the api to return a 503 error.
I noticed the issue when logging out chunk and http_error with a custom delegate, it shows that the start position increments even if there is an error: 
```
chunk: ContentRange { range: Some(Chunk { first: 0, last: 8388607 }), total_length: 639445126 }
chunk: ContentRange { range: Some(Chunk { first: 8388608, last: 16777215 }), total_length: 639445126 }
chunk: ContentRange { range: Some(Chunk { first: 16777216, last: 25165823 }), total_length: 639445126 }
chunk: ContentRange { range: Some(Chunk { first: 25165824, last: 33554431 }), total_length: 639445126 }
chunk: ContentRange { range: Some(Chunk { first: …
```
> Fix resumable uploads

- src/mako/api/lib.rs.mako
- src/mako/api/lib/lib.mako
Fix #307
This PR can be tested by:
- generating the new rust code by running  `make drive3-cli-cargo ARGS=check` inside the google-apis-rs folder
- Creating an empty project and specifying a dependency to the new code
```toml
[dependencies]
google-drive3 = {path = "../google-apis-rs/gen/drive3"} # path to generated gdrive api
```
- Writing a minimal example inside this new project:
```rust
fn main() {
let hub = google_drive3::DriveHub::new(
google_drive3::hyper::Client::builder().build(
google_drive3::hyper_rustls::HttpsConnector::with_native_roots()
),
todo!()
);
}
```
- Checking this new project: `cargo check`
> Fix #307 by reexporting publicly hyper and hyper_rustls

- etc/api/bigquery/v2/bigquery-api_overrides.yaml
- gen/bigquery2/src/api.rs
BQ job.insert supports metadata-only job creation. I needed this for something.
not sure if I'm intended to include the gen'd code in the pr or if there's other tasks that need to be run.
(sorry, clicked the wrong branch...)
> bigquery: add non-uploading job.insert rpc

- Cargo.toml
- requirements.txt
- src/generator/templates/Cargo.toml.mako
- src/generator/templates/api/api.rs.mako
- src/generator/templates/api/lib/mbuild.mako
- src/generator/templates/cli/mkdocs.yml.mako
- src/rust/api/client.rs
Note: New PR without generated API files.
I decided to give the "decouple" approach a try, as it fits my needs better.
I took the approach of creating an `Authenticator` trait which allows tokens to be generated asynchronously (as approached to the delegate, which requires sync). I believe the crates should still work as before for anyone not using a custom `Delegate` trait, as `Hub::new` accepts an instance of `Authenticator`, which is implemented for `yup_oauth2::authenticator::Authenticator`.
`yup-oauth2` is no longer a required dependency, and can be disabled if a user should choose to do so by using `default-features = false`. 
The only breaking change introduced is `err` parameter from the `Delegate::token` method. Given that the `Authenticator` implementation can handle any …
>  Use generic Authy trait in place of yup_oauth2

- google-apis-common/src/lib.rs
I apparently missed a few necessary trait bounds while implementing `GetToken`, which I discovered while using the crate in my project. I've added the necessary bound plus a test to ensure that it remains correct in the future.
Unfortunately, I think this might necessitate yanking the previous versions of google-apis-common (as they will likely fail to compile).
> Add missing trait bounds for proper async to GetToken

- google-apis-common/src/lib.rs
- src/generator/templates/api/api.rs.mako
- src/generator/templates/api/lib/mbuild.mako
I'm not sure whether these changes should be included in the previous PR - but given that it's non-essential, I've decided to keep them separate. 
The first change is refactoring `remove_json_null_values` to run in linear time (the `arr.remove()` call takes `O(n)` time and may be  called `n` times, which could accidentally lead to quadratic run times) - this incidentally makes the code a lot cleaner.
The second change is using `tokio::time::sleep` in place of `std::thread::sleep` in the upload functions (for both `google-apis-common` and `api.rs`). `std::thread::sleep` is blocking per https://doc.rust-lang.org/stable/std/thread/fn.sleep.html, and should not be used in async functions.
> Refactor client functions

- google-apis-common/Cargo.toml
- google-apis-common/src/field_mask.rs
- google-apis-common/src/lib.rs
- google-apis-common/src/serde.rs
- src/generator/lib/__tests__/util_test.py
- src/generator/lib/rust_type.py
- src/generator/lib/util.py
- src/generator/templates/api/api.rs.mako
- src/generator/templates/api/lib.rs.mako
- src/generator/templates/api/lib/lib.mako
- src/generator/templates/api/lib/mbuild.mako
- src/generator/templates/api/lib/schema.mako
This is a draft PR which includes the basic fix, allowing more values to be deserialized correctly. 
To handle Google specific types, I've included a rudimentary implementation for base64 and `Duration` encode/decode.
The `Duration` struct can simply be imported where necessary, and implements serde directly.
However, the base64 encoding / decoding requires custom attributes to utilize the appropriate serde functions (as we'd want it to be `Vec<u8>`). 
This leaves 3 date-time types, and one fieldmask type. Unfortunately, it is somewhat difficult to track down the concrete type definitions, so I'm not entirely confident that the implementations thus far are correct.
However, I think this go package might be relevant: https://pkg.go.dev/google.golang.org/protobuf/types
(Incidentally, it …
> Use schema format over type

- src/generator/lib/util.py
- src/generator/templates/api/lib/mbuild.mako
- src/generator/templates/api/lib/rbuild.mako
- `add_scope` is simplified to simply add scopes, and no longer takes an `Option<_>` item.
- Added `add_scopes` convenience function, which allows adding multiple scopes at once. 
- Added `clear_scopes` function to explicitly allow clearing method scopes.
This also includes small improvements to documentation - primarily by including links to referenced types / methods
Addresses #333
> Refactor modification of scopes

- .github/workflows/rust.yml
- google-apis-common/Cargo.toml
- google-apis-common/src/auth.rs
- google-apis-common/src/lib.rs
- src/generator/templates/Cargo.toml.mako
- src/generator/templates/api/api.rs.mako
- src/generator/templates/api/lib.rs.mako
- src/generator/templates/api/lib/mbuild.mako
Since we're moving on to the next API version, I'm revisiting this change as well.
PR includes:
- Documentation on how to use authentication, and how to implement custom authenticators as needed
- More flexible authentication error types
- Optional `yup-oauth2` (included by default)
- Optional token for APIs which optionally require token.
I'd also like to see about entirely removing the `yup-oauth2` dependency for (and `auth` argument in Hub constructor) for unauthenticated APIs
> Auth refactor

- .github/workflows/rust.yml
- google-apis-common/Cargo.toml
- google-apis-common/src/field_mask.rs
- google-apis-common/src/lib.rs
- google-apis-common/src/serde.rs
- google-apis-common/src/url.rs
- google-clis-common/Cargo.toml
- google-clis-common/src/lib.rs
- src/generator/lib/cli.py
- src/generator/lib/types.py
- src/generator/lib/util.py
- src/generator/templates/api/lib/mbuild.mako
- src/generator/templates/cli/lib/engine.mako
- src/generator/templates/cli/main.rs.mako
- src/rust/preproc/src/main.rs
This refactors the shared url parameter functionality into `google-apis-common`. 
This is good for testing, and reduces the amount of mako-specific code-gen, which is nice. This also reduces the size of the generated `compute1` library by 2.4%, from 168MB to 164MB (and compile times from 43s to 35s, though I don't know if this is due to other effects).
Additionally, I noticed that the `url` crate is very out of date - however, I have no idea where to update this dependency, as my initial grep failed to find anything.
> Refactor params into google-apis-common

- google-apis-common/Cargo.toml
- google-apis-common/src/auth.rs
- google-clis-common/Cargo.toml
yup-oauth2 supports impersonating service accounts in 8.0, which is a very useful feature.
Here's an attempt to bump the dep in google-apis-common.
> Update yup-oauth2 to 8.0.0

- requirements.txt
- src/generator/lib/util.py
The generator tries to turn plural into singular nouns. However, some words turn out badly, including:
- Addresse (from Addresses)
- Prefixe (from Prefixes)
- Bookshelve (from Bookshelves)
- Sery (from Series)
By using a library, we can get a slightly better outcome. I've added an exception for "Data", because seeing that turned into "Datum" is a bit jarring.
For the above, the resulting generated word:
- Address
- Prefix
- Bookshelf
- Series
> Improve handling of plurals in generator.

- google-apis-common/Cargo.toml
Chrono currently depends on an old version of time with a reported vulnerability: https://rustsec.org/advisories/RUSTSEC-2020-0159
While it does not use any vulnerable code, the dependency may show up in code vulnerability scans, etc.
This removes the "oldtime" feature from chrono, to remove that. Also removes the "std" feature because it doesn't seem to be in use in this code.
> Remove old time dependency from API.

- google-apis-common/Cargo.toml
- src/generator/templates/Cargo.toml.mako
I ran cargo update in my crate and I noticed I was getting compile errors due to the versions of `hyper-rustls` used by the generated API crates don't match the version of `hyper-rustls` used by the `yup-oauth2` crate version `8.2`
> Match version of hyper-rustls used by yup-oauth2 8.2.0

- gen/youtube3/src/api.rs
- src/generator/templates/api/lib/lib.mako
Adding that makes logging and debugging easier.
> Add Debug derive to youtube3::api::Scope enum

- google-apis-common/src/serde.rs
- src/generator/lib/rust_type.py
- src/generator/lib/util.py
> Attempt to add 'standard' base64 bytes support

- google-apis-common/src/field_mask.rs
The inner value was private so it couldn't be constructed directly (without deserializing from a string indirectly).  Creating it directly seems safer than deserializing, especially since I'm unfamiliar with the format.
Was it intended for this to be constructed directly or is there another mechanism for setting these up? I thought the api might do it directly but it doesn't atm afaict.
> Make field mask inner public

- google-apis-common/src/serde.rs
In our use case, we deserialize GCP structs using a file reader (instead from an in-memory string), which yields errors such as this is:
```
Caused by:
invalid type: string "...", expected a borrowed string at line ... column ...
```
The first commit demonstrates this behavior, and the second fixes it by allow `serde` to choose between a borrowed an owned string using a `Cow`.
> Fix base64 deserialization when using a reader

- google-clis-common/Cargo.toml
- src/generator/templates/Cargo.toml.mako
- src/generator/templates/api/lib/lib.mako
- src/generator/templates/cli/main.rs.mako
> Update yup-oauth2 to 8.3.3 and hyper-rustls to 0.25

- google-apis-common/Cargo.toml
I have missed this in #482. The current specification still allows 8.3.3, but is good to set this lower limit still. It is not going to compile with anything lower.
> Update yup-oauth2 in google-apis-common

- google-clis-common/src/lib.rs
The clippy action currently fails due to a direct implementation fo ToString instead of Display
The error message is:
```
error: direct implementation of `ToString`
--> google-clis-common/src/lib.rs:128:1
|
| / impl ToString for FieldCursor {
| |     fn to_string(&self) -> String {
| |         self.0.join(".")
| |     }
| | }
| |_^
|
= help: prefer implementing `Display` instead
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#to_string_trait_impl
= note: `-D clippy::to-string-trait-impl` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::to_string_trait_impl)]`
```
> Fix clippy complaining about "direct implementation of `ToString`"

- src/generator/lib/rust_type.py
- src/generator/lib/util.py
Some fields are encoded as base64 URL instead of Base64 Standard. This tries to catch fields requiring URL encoding by searching the description for specific words.
I'm not happy with the current implementation but I'm not too familiar with Python. Any suggestions on how to avoid the `description` parameter on `serde_as`?
This resulted into the following diff:
```diff
diff --git a/gen/drive2/src/api.rs b/gen/drive2/src/api.rs
index 7f30911f30..cb2689d1ff 100644
--- a/gen/drive2/src/api.rs
+++ b/gen/drive2/src/api.rs
@@ -3019,7 +3019,7 @@ impl client::Part for FileShortcutDetails {}
pub struct FileThumbnail {
/// The URL-safe Base64 encoded bytes of the thumbnail image. It should conform to RFC 4648 section 5.
-    #[serde_as(as = "Option<::client::serde::standard_base64::Wrapper>")]
+ …
```
> Detect fields using base64 URL encoding

- google-apis-common/src/serde.rs
Attempts to decode `bytes` fields in response JSON using both `standard` and `url_safe` encodings.  The expected encoding's desierializer is tried first.  On error the second is attempted.  If the second fails, the original error from the first is returned.
Fixes https://github.com/Byron/google-apis-rs/issues/502
Likely fixes other bugs too but I haven't tested
> Tolerant base64 decoding.  Accept url-safe or standard encoding in responses.

- src/generator/lib/util.py
- src/generator/templates/Cargo.toml.mako
- src/generator/templates/api/api.rs.mako
- src/generator/templates/api/lib/lib.mako
- src/generator/templates/api/lib/schema.mako
I needed this feature because our consuming API needs to generate docs for the frontend client but could not because of Rust's orphan rule.
This is PR is incomplete, I think it would be better to put this feature in a feature flag because everyone would not need it.
Please validate that this feature is a good idea.
> Derive utoipa::ToSchema by default for generating openapi specs by other libraries

- apis.json
- etc/api/api-list.yaml
- etc/api/cloudcommerceprocurement/v1/cloudcommerceprocurement-api.json
Adds:
- cloudcommerceprocurement v1
I tried to do the same thing as https://github.com/Byron/google-apis-rs/pull/515 did.
I was able to use this crate successfully in my own project (private repo unfortunately).
> Add cloudcommerceprocurement API

- .github/workflows/ci.yml
- Makefile
- google-apis-common/Cargo.toml
- google-apis-common/src/lib.rs
- src/generator/templates/Cargo.toml.mako
- src/generator/templates/api/lib/mbuild.mako
Previously, I defined the body to be `Full<Bytes>`, which meant that the response would have to be fully received inside the API functions. However, that seems wasteful if one wants to do some streaming processing of the incoming data. This PR switches over to `http_body_util::combinators::BoxBody`, which is what is [recommended](https://hyper.rs/guides/1/upgrading/) in cases of having to accommodate different response types.
> Avoid processing incoming bodies unnecessarily

- apis.json
- etc/api/api-list.yaml
- etc/api/places/v1/places-api.json
- gen/places1/Cargo.toml
- gen/places1/LICENSE.md
- gen/places1/README.md
- gen/places1/src/api.rs
- gen/places1/src/lib.rs
> chore: add places api v1

- google-clis-common/src/lib.rs
- src/generator/templates/Cargo.toml.mako
This requires serde_json >= 1.0.130 (latest: 1.0.140)
It seems that version of serde_json pinned loosely to "1":
```
src/generator/templates/Cargo.toml.mako:serde_json = "1"
```
Thus, a rebuild should work.
Should I also upgrade to `serde_json = "1.0.130"`?
Closes #542
> fix command-line argument parsing of integers

- etc/api/gmail/v1/gmail-api.json
- gen/gmail1/Cargo.toml
- gen/gmail1/README.md
- gen/gmail1/src/api.rs
- gen/gmail1/src/lib.rs
- gen/storage1-cli/Cargo.toml
- gen/storage1-cli/README.md
- gen/storage1-cli/mkdocs.yml
- gen/storage1-cli/src/main.rs
- google-apis-common/src/field_mask.rs
- google-apis-common/src/lib.rs
- google-apis-common/src/serde.rs
- google-clis-common/src/lib.rs
- src/generator/templates/cli/lib/engine.mako
Users experience "Missing access token for authorization" errors when calling individual Gmail message operations with valid OAuth2 tokens that have standard Gmail scopes:
- ✅ `messages().list()` works correctly
- ❌ `messages().get()` fails with 403 authorization error
- ❌ `threads().get()` fails with 403 authorization error  
- ❌ `messages().attachments().get()` fails with 403 authorization error
This occurs even when users have proper `gmail.readonly`, `gmail.modify`, or `gmail.compose` scopes.
**Inconsistent OAuth2 scope defaults** in the Gmail API discovery document:
- `messages.list()` correctly defaults to `gmail.readonly` scope
- `messages.get()`, `threads.get()`, `attachments.get()` incorrectly default to `gmail.addons.current.message.readonly` scope
The addon-specific scope is …
> fix(gmail1): Correct OAuth2 scope precedence for message operations

- etc/api/shared.yaml
- gen/homegraph1/Cargo.toml
- gen/homegraph1/LICENSE.md
- gen/homegraph1/README.md
- gen/homegraph1/src/api.rs
- gen/homegraph1/src/lib.rs
- src/generator/lib/util.py
I'm not sure why the solution to `async` being a keyword was blacklisting instead of adding `async` to the long list of reserved keywords. So this PR removes homegraph1 from the blacklist and adds the gen back.
I would welcome guidance on what to do to "release" a new version of the crate, in this PR or as a follow-up.
Also: fixes the comment about the blacklist in `shared.yaml`, which somehow moved to a random item within.
> fix(homegraph1): Un-blacklist by adding 'async' to reserved words
