- Cargo.toml
- src/rust/cli/cmn.rs
- src/rust/lib.rs
> fix(cmn): get cmn compiling on nightly rust

- src/mako/Cargo.toml.mako
- src/rust/api/cmn.rs
> Depend on hyper 0.7.0

- etc/api/shared.yaml
- gen/sheets4-cli/Cargo.toml
- gen/sheets4-cli/LICENSE.md
- gen/sheets4-cli/README.md
- gen/sheets4-cli/mkdocs.yml
- gen/sheets4-cli/src/cmn.rs
- gen/sheets4-cli/src/main.rs
- gen/sheets4/Cargo.toml
- gen/sheets4/LICENSE.md
- gen/sheets4/README.md
- gen/sheets4/src/cmn.rs
- gen/sheets4/src/lib.rs
- src/mako/lib/util.py
Sheets api has a 'values' key in resources.spreadsheets.resources which collided with activities.values(). Using iteritems to iterate instead.
> Fix for util.py to allow for sheets api to be built

- etc/api/api-list.yaml
- etc/api/photoslibrary/v1/photoslibrary-api.json
- etc/api/shared.yaml
- gen/photoslibrary1/Cargo.toml
- gen/photoslibrary1/LICENSE.md
- gen/photoslibrary1/README.md
- gen/photoslibrary1/src/cmn.rs
- gen/photoslibrary1/src/lib.rs
- src/mako/deps.mako
The photoslibrary API is not listed however is still available.
This adds a method of manually adding APIs to the shared.yaml and adds the photoslibary API info.
Fixes #198
> Photoslibrary

- etc/api/type-api.yaml
- src/mako/api/lib/mbuild.mako
Hi Byron.
I've seen your videos on how you did it and I'll like to thank you for this work.
After seeing this, I ask myself, how can I help you with my basic skill...
And update Url dep from 0.5.1 to 1.7.1
> Update dep url to 1.7.1

- .travis.yml
The Travis Yaml file was invalid after #205
> Fix Travis Yaml file

- .gitignore
- Makefile
- requirements.txt
- src/mako/api/lib/mbuild.mako
- src/mako/api/lib/rbuild.mako
- src/mako/lib/test_data/photoslibrary-api.json
- src/mako/lib/util.py
- src/mako/lib/util_test.py
Add tests to Utils.to_rust_type. This is the code the converts types found in the Google Schema to usable Rust types.
This does change some code slightly and also wires in code coverage metrics.
> Python type testing

- .travis.yml
- src/mako/Cargo.toml.mako
Fixes https://github.com/Byron/google-apis-rs/issues/236
I didn't include everything that changed in gen as I'm still running tests and there are a lot of mako errors on my machine. I can include them if needed.
> Expose features from yup-oauth2

- .gitignore
- Makefile
- etc/bin/mako-render
- requirements.txt
- src/mako/api/lib.rs.mako
- src/mako/api/lib/lib.mako
- src/mako/api/lib/mbuild.mako
- src/mako/api/lib/rbuild.mako
- src/mako/api/lib/schema.mako
- src/mako/cli/docs/commands.md.mako
- src/mako/cli/lib/argparse.mako
- src/mako/cli/lib/engine.mako
- src/mako/deps.mako
- src/mako/lib/cli.py
- src/mako/lib/util.py
An attempt to migrate everything to python3 and the latest mako.
So far it works suprisingly well.
When done, the PR #259 can be handled.
> toolchain update

- src/mako/api/lib/mbuild.mako
- src/rust/api/client.rs
@Byron here is a pull request for the fix that we talked about in https://github.com/Byron/google-apis-rs/pull/264#issuecomment-811995650
I had originally made it as a pull request here:
https://github.com/djrodgerspryor/google-apis-rs/pull/1
but it didn't get merged in time, so now I will just make the merge request directly to you 😃
> Bug fix: It was not possible to use FileGetCall to download binary files

- src/rust/api/client.rs
- src/rust/cli/client.rs
See issue https://github.com/Byron/google-apis-rs/issues/266.
> Fix truncated responses + clean up (cargo clippy + cargo fmt)

- gen/storage1/src/client.rs
- src/rust/api/client.rs
> Correct multipart line endings

- src/mako/api/lib.rs.mako
- src/mako/api/lib/lib.mako
- src/mako/cli/lib/engine.mako
- src/mako/cli/main.rs.mako
- src/mako/lib/util.mako
- src/rust/cli/client.rs
> Expose yup_oauth2 crate from inside the crates

- src/mako/api/lib/mbuild.mako
- src/rust/api/client.rs
Addresses https://github.com/Byron/google-apis-rs/issues/314
> Refactor server errors management

- gen/drive3/README.md
- gen/drive3/src/api.rs
- gen/drive3/src/client.rs
- gen/drive3/src/lib.rs
- src/rust/api/client.rs
Fixes https://github.com/Byron/google-apis-rs/issues/347
> Resolves 'Panic on http2 timeout '

- src/generator/lib/util.py
- src/generator/templates/api/api.rs.mako
- src/generator/templates/api/lib/mbuild.mako
This PR includes some smaller fixes to the internal implementations. My end-goal is to simplify the logic and move as much functionality as possible into reusable functions, in order to reduce the binary size of the underlying libraries and ensure correctness by allowing individual components to be unit tested.
This includes 4 commits, each of which are hopefully self-explanatory - I've decided to include them in one PR to keep things simple.
I think the `add_scope` function should be simplified / refactored somewhat, as it both doesn't match the documentation, and should take a simpler set of parameters. In particular, the documentation states that `None` values will clear the scopes, but they don't actually do this. This also seems like an overly complicated implementation, and I think …
> Code quality

- gen/androidpublisher3/src/api.rs
- src/generator/templates/api/lib/mbuild.mako
> fixed Content-Length with empty body

- etc/api/api-list_travis.yaml
- etc/api/shared.yaml
- src/generator/lib/types.py
- src/generator/lib/util.py
Hello,
Here are the changes needed for Spanner to be generated and successfully tested.
I am not sure what the protocol is. Should I include the generated package into the same PR? But then it looks like the generated bindings are outdated with respect to the JSON files in the repository (probably also related to #482), and the JSON files in the repository are outdated with respect to the official reference. It would be nice to bring everything up to seed. I can do that separately if you want.
Closes #484.
> Add support for Spanner

- google-apis-common/Cargo.toml
- google-clis-common/Cargo.toml
> Update yup-oauth2 to version 9

- src/generator/templates/deps.mako
It was originally failing, but then I cleaned up the templates, and it started to pass. Forgot to remove the echo.
> Format the CLIs

- src/generator/lib/util.py
Hi @Byron! 
Thank you for the feedback on the previous PR. I didn't realise that `etc/` was also regenerated,  I assumed initially that it was just `gen/`! So I've implemented a **persistent solution** that addresses the root cause directly in the code generator.
The original OAuth2 scope issue stemmed from the generator's `method_default_scope()` function using simple alphabetical sorting (`sorted(m.scopes)[0]`) to select default scopes. This caused Gmail API methods to default to restrictive addon-specific scopes like `gmail.addons.current.message.readonly` instead of the standard user-accessible `gmail.readonly` scope.
Instead of patching individual API files, I've enhanced the scope selection logic in the generator itself:
**Modified `src/generator/lib/util.py`:**
- Enhanced …
> feat: implement persistent OAuth2 scope precedence ordering
